spring:
  application:
    name: gateway-service-zuul
zuul:
  routes:
    api-a:
      path: /api-gateway/**
      url: http://localhost:8763/
server:
  port: 8764
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


#增加路由规则的配置
#通过zuul.routes.<route>.path和zuul.routes.<route>.url进行配置，<route>为路由的名字，可以任意指定，但是一组path和url的路由名要相同
#zuul.routes.baidu.path: /baidu/**
#zuul.routes.baidu.url: http://www.baidu.com

